# Numpy

In [12]:
import numpy as np

In [13]:
myarr = np.array([4, 2, 14, 2])

In [14]:
myarr

array([ 4,  2, 14,  2])

In [15]:
myarr.dtype

dtype('int32')

## Array creation

In [16]:
listarray = np.array([[4,3,5], [2,6,33],[2, 2, 9]])

In [17]:
listarray

array([[ 4,  3,  5],
       [ 2,  6, 33],
       [ 2,  2,  9]])

In [18]:
listarray.shape

(3, 3)

In [19]:
listarray.size

9

### np.zeros()

In [29]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [20]:
zeros = np.zeros((2,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
np.zeros((2,3), int)

array([[0, 0, 0],
       [0, 0, 0]])

### np.ones()

In [33]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

### np.arange()

In [21]:
rng = np.arange(13)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

- by default starts from zero. 13 is not included

In [28]:
b = np.arange(4,20)
b

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

- 4 : start number
- 20 : end number (not included)

In [31]:
np.arange(3,20,3)

array([ 3,  6,  9, 12, 15, 18])

- 3 : start number
- 20 : end number (not included)
- 3 : common difference

### np.linspace()

In [22]:
lspace = np.linspace(1, 50, 10)
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

- 1 : start number
- 50 : end number
- 10 : no of elements
- equally spaced numbers

### np.empty()

In [32]:
emp = np.empty((2,4))
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.27945906e-307],
       [1.89146896e-307, 7.56571288e-307, 3.11525958e-307,
        1.24610723e-306]])

- random uninitialized values

### np.eye()

In [36]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

- identity matrix

### np.identity()

In [34]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

- identity matrix

### np.random()

In [38]:
np.random.rand(3,5)

array([[0.5654853 , 0.62935978, 0.49053486, 0.98037661, 0.81759374],
       [0.06398444, 0.9811496 , 0.5139895 , 0.33052281, 0.98091328],
       [0.32324969, 0.31814398, 0.44875338, 0.58431104, 0.65909145]])

- it generates random number form uniform distribution (between 0 and 1)

In [43]:
np.random.randn(3,4)

array([[-0.22063292,  1.73725383,  1.85114409,  0.56396053],
       [ 0.76296186, -1.05281224, -1.22535844,  0.56594412],
       [-0.43223329,  0.0468747 , -0.88099922, -0.22214235]])

-  It generates a random number from the standard normal distribution (also known as the Gaussian distribution)

In [57]:
np.random.randint(10,20)

11

- random integer in [10,20)
- 20 is not included

In [58]:
np.random.randint(10,32,50)

array([16, 17, 17, 29, 29, 22, 16, 21, 22, 20, 22, 24, 25, 24, 17, 29, 30,
       31, 15, 15, 12, 16, 29, 12, 21, 11, 26, 24, 15, 17, 15, 13, 17, 27,
       23, 19, 16, 11, 17, 26, 13, 26, 29, 11, 27, 18, 13, 11, 25, 10])

- 10 : lower bound
- 32 : upper bound (not included)
- 50 : size

## Some functions and methods

In [115]:
arr = np.random.randint(0,100,20)
arr

array([32, 42, 83, 26, 18, 80, 28, 22, 90, 94, 93, 98,  1, 17, 31, 65, 28,
       91, 63, 45])

In [116]:
arr.reshape(5,4)

array([[32, 42, 83, 26],
       [18, 80, 28, 22],
       [90, 94, 93, 98],
       [ 1, 17, 31, 65],
       [28, 91, 63, 45]])

- size of arr is 20, so in <font color=orange>arr.reshape(a,b)</font>, $a*b$ should be 20. Otherwise it will through an error.

In [117]:
arr.min()

1

In [118]:
arr.argmin()

12

- it gives index of minimun value

In [119]:
arr.max()

98

In [120]:
arr.argmax()

11

- it gives index of maximum value

In [121]:
arr.argsort()

array([12, 13,  4,  7,  3, 16,  6, 14,  0,  1, 19, 18, 15,  5,  2,  8, 17,
       10,  9, 11], dtype=int64)

In [68]:
arr.dtype

dtype('int32')

In [70]:
arr2 = np.eye(5)
arr2

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [72]:
arr2.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

- <font color=orange>arr2.T</font> gives transpose of arr2

In [73]:
arr3 = np.random.rand(2,3)
arr3

array([[0.96357352, 0.40999179, 0.35889557],
       [0.61998824, 0.69904961, 0.54917697]])

In [74]:
arr3.T

array([[0.96357352, 0.61998824],
       [0.40999179, 0.69904961],
       [0.35889557, 0.54917697]])

In [108]:
arr3.ravel()

array([0.96357352, 0.40999179, 0.35889557, 0.61998824, 0.69904961,
       0.54917697])

- converts an array to a 1D array

## Examples

In [75]:
arr4 = np.arange(5,25)
arr4

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [76]:
arr4[-4]

21

In [77]:
arr4[4:9]

array([ 9, 10, 11, 12, 13])

- it slices _arr4_ from 4th index to 8th index, 9th index is not included

In [79]:
arr4[4:9] = 100
arr4

array([  5,   6,   7,   8, 100, 100, 100, 100, 100,  14,  15,  16,  17,
        18,  19,  20,  21,  22,  23,  24])

In [81]:
arr4[:] = 99
arr4

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
       99, 99, 99])

## Two-Dimensional Array

In [82]:
matr = np.array(([32, 41, 12, 32], [2, 45, 67, 23], [23, 43, 1, 99]))
matr

array([[32, 41, 12, 32],
       [ 2, 45, 67, 23],
       [23, 43,  1, 99]])

In [83]:
matr[0][2]

12

- 0 : row
- 2 : column

In [84]:
matr[2,:]

array([23, 43,  1, 99])

- 2 : row
- colon stands for all. So here it is all column

In [86]:
matr[2]

array([23, 43,  1, 99])

In [87]:
matr[:, (3,2)]

array([[32, 12],
       [23, 67],
       [99,  1]])

In [112]:
matr.ndim # no of dimension

2

In [113]:
matr.nbytes

48

- all rows
- 3rd and 1st index column

## Selection techniques

In [88]:
arr5 = np.arange(1,20)
arr5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [89]:
arr5 + arr5

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [90]:
np.exp(arr5)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

- exponential, that is $e^x$

In [91]:
np.sqrt(arr5)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [92]:
np.log(arr5)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [93]:
np.min(arr5)

1

In [94]:
np.argmin(arr5)

0

In [96]:
np.max(arr5)

19

In [97]:
np.argmax(arr5)

18

In [98]:
np.square(arr5)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [99]:
np.std(arr5)

5.477225575051661

In [100]:
np.var(arr5)

30.0

In [102]:
np.mean(arr5)

10.0

In [103]:
arr6 = np.random.randn(3,4)
arr6

array([[ 0.04170211, -0.98041077,  0.43394012, -0.56713664],
       [-0.13120636,  1.07112093,  1.32165448,  0.8244754 ],
       [-1.28233444, -0.55901377,  1.6300761 ,  1.0190845 ]])

In [104]:
np.round(arr6, 3)

array([[ 0.042, -0.98 ,  0.434, -0.567],
       [-0.131,  1.071,  1.322,  0.824],
       [-1.282, -0.559,  1.63 ,  1.019]])

In [106]:
sports = np.array(['golf', 'cricket', 'football', 'cricket', 'football'])
sports

array(['golf', 'cricket', 'football', 'cricket', 'football'], dtype='<U8')

In [107]:
np.unique(sports)

array(['cricket', 'football', 'golf'], dtype='<U8')

- Unique element
- in <font color = orange> dtype='<U8'</font> , 8 is the length of longest value